/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AdminRole;
import backend.LibrarianUser;
import constants.FileNames;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Blu-Ray
 */
public class AddLibrarian extends javax.swing.JFrame implements Node {
    /**
     * Creates new form AddLibrarians
     */
    public AddLibrarian() {
        initComponents();
    }

    private Node parent;

    /**
     * Creates new form AddLibrarians
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        librarianEmailLabel = new javax.swing.JLabel();
        librarianIdTextField = new javax.swing.JTextField();
        librarianIdLabel = new javax.swing.JLabel();
        librarianAddressLabel = new javax.swing.JLabel();
        librarianNameLabel = new javax.swing.JLabel();
        librarianPhoneLabel = new javax.swing.JLabel();
        librarianAddressTextField = new javax.swing.JTextField();
        librarianEmailTextField = new javax.swing.JTextField();
        librarianPhoneTextField = new javax.swing.JTextField();
        librarianNameTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Librarian");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        librarianEmailLabel.setBackground(new java.awt.Color(0, 255, 0));
        librarianEmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        librarianEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        librarianEmailLabel.setText("Email");
        librarianEmailLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librarianEmailLabel.setOpaque(true);

        librarianIdLabel.setBackground(new java.awt.Color(0, 255, 0));
        librarianIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        librarianIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        librarianIdLabel.setText("Librarian Id");
        librarianIdLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librarianIdLabel.setOpaque(true);

        librarianAddressLabel.setBackground(new java.awt.Color(0, 255, 0));
        librarianAddressLabel.setForeground(new java.awt.Color(0, 0, 0));
        librarianAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        librarianAddressLabel.setText("Address");
        librarianAddressLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librarianAddressLabel.setOpaque(true);

        librarianNameLabel.setBackground(new java.awt.Color(0, 255, 0));
        librarianNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        librarianNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        librarianNameLabel.setText("Name");
        librarianNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librarianNameLabel.setOpaque(true);

        librarianPhoneLabel.setBackground(new java.awt.Color(0, 255, 0));
        librarianPhoneLabel.setForeground(new java.awt.Color(0, 0, 0));
        librarianPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        librarianPhoneLabel.setText("Phone Number");
        librarianPhoneLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librarianPhoneLabel.setOpaque(true);

        librarianNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(librarianPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(librarianAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librarianEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librarianIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librarianNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(librarianPhoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(librarianAddressTextField)
                    .addComponent(librarianEmailTextField)
                    .addComponent(librarianIdTextField)
                    .addComponent(librarianNameTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setBackground(new java.awt.Color(0, 0, 0));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        String librarianId = librarianIdTextField.getText();
        String librarianName = librarianNameTextField.getText();
        String librarianEmail = librarianEmailTextField.getText();
        String librarianAddress = librarianAddressTextField.getText();
        String librarianPhone = librarianPhoneTextField.getText();
        AdminRole admin = new AdminRole();
        if (librarianId.equals("") || librarianName.equals("") || librarianEmail.equals("") || librarianAddress.equals("") || librarianPhone.equals("")) {
            JOptionPane.showMessageDialog(null, "Some fields are empty");
        } 
        else {
            int numOfLibrarians = admin.getListOfLibrarians().length;
            admin.addLibrarian(librarianId, librarianName, librarianEmail, librarianAddress, librarianId);
            int newNumOfLibrarians = admin.getListOfLibrarians().length;
            if(numOfLibrarians == newNumOfLibrarians)
                JOptionPane.showMessageDialog(null, "The librarian with ID = " + librarianId + " already exists!");
            else{
                librarianIdTextField.setText("");
                librarianNameTextField.setText("");
                librarianEmailTextField.setText("");
                librarianAddressTextField.setText("");
                librarianPhoneTextField.setText("");
                JOptionPane.showMessageDialog(null, "The librarian with id = " + librarianId + " has been successfully added!");
                admin.logout();
            }
        } 
    }//GEN-LAST:event_addButtonActionPerformed

    private void librarianNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librarianNameTextFieldActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLibrarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel librarianAddressLabel;
    private javax.swing.JTextField librarianAddressTextField;
    private javax.swing.JLabel librarianEmailLabel;
    private javax.swing.JTextField librarianEmailTextField;
    private javax.swing.JLabel librarianIdLabel;
    private javax.swing.JTextField librarianIdTextField;
    private javax.swing.JLabel librarianNameLabel;
    private javax.swing.JTextField librarianNameTextField;
    private javax.swing.JLabel librarianPhoneLabel;
    private javax.swing.JTextField librarianPhoneTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
}
